# Generated by Django 5.1 on 2024-11-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_products_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_featured',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
