# Generated by Django 5.1 on 2024-09-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('fb', models.CharField(max_length=500)),
                ('git', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
    ]
