# Generated by Django 5.1 on 2024-09-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_about_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
                ('s_description', models.CharField(max_length=500)),
            ],
        ),
    ]
