# Generated by Django 5.1 on 2024-09-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='s_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
