# Generated by Django 5.1 on 2024-09-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_about_s_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='s_image',
            field=models.ImageField(default=1, upload_to='services/'),
            preserve_default=False,
        ),
    ]
