# Generated by Django 5.1 on 2024-10-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Categories',
        ),
    ]
